version: '2.2'

services:
  web:
    image: arm64v8/php:7.4-apache
    hostname: lampp-php7.4
    container_name: lampp-php7.4
    ports:
      - "8090:80"
      - "8022:22"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    mem_limit: 256m
    cpus: 1.0

  db:
    image: bitnami/mysql:5.7
    container_name: lampp-mysql5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./mysql:/var/lib/mysql
    mem_limit: 256m
    cpus: 1.0

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: lampp-phpmyadmin5.2.2
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
    mem_limit: 256m
    cpus: 1.0

  web8:
    image: arm64v8/php:8.0-apache
    hostname: lampp-php8.0
    container_name: lampp-php8.0
    ports:
      - "8190:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mariadb
    mem_limit: 256m
    cpus: 1.0

  mariadb:
    image: arm64v8/mariadb:10.5
    container_name: lampp-mariadb10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: langgar69
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./mariadb:/var/lib/mysql
    mem_limit: 256m
    cpus: 1.0

  phpmyadmin8:
    image: arm64v8/phpmyadmin
    container_name: lampp-phpmyadmin-mariadb
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8191:80"
    environment:
      PMA_HOST: mariadb
    mem_limit: 256m
    cpus: 1.0
